### ISSUE TITLE
Not compatible with multiple processes

### ISSUE THREAD

**Issue by btimby** [Nekmo/geoip2-tools#5]
* geoip2-tools version: master
* Python version: 3.8
* Operating System: Alpine Linux

### Description

I am using this library in a tool and part of the use-case is to run multiple processes. This creates a condition where each process is performing the download in parallel and due to the global file name, these processes "race". i.e. one process deletes the '.tar.gz' file while another process is opening it.

### What I Did

My code is simply:
```
    # Trigger download of geoip database.
    db = GEOIP['city']
```

### Solution
To work around this, I forked your repository and I am using `tempfile.mkstemp()` to create a "private" file name for each process. This works but is not desirable since it causes the download of the database for each process (and if you run the process again, the database will not be discoverable).

My plan is to introduce a lock file around the download procedure so that the first process (race winner) will perform the download and the remaining processes will wait for the file to be available.

Is this a change you would accept in a PR?

**Comment by btimby** [comment]
This PR introduces locking.

https://github.com/Nekmo/geoip2-tools/pull/6

**Comment by Nekmo** [comment]
I'm going to look at the pull request, I think it's a necessary feature. Thanks!

**Comment by Nekmo** [comment]
Thanks @btimby !
